# GitHub Actions workflow to upload test reports after the tests.yml workflow.
# (This is a separate workflow in order to allow test reports on forked repositories.)

name: Test reports

on:
  # Run this workflow automatically after the "Unit tests" workflow has completed.
  workflow_run:
    workflows:
      - "Unit tests"
    types:
      - completed

jobs:
  report:
    name: Publish unit test reports
    runs-on: ubuntu-latest

    steps:
      - name: Publish unit test reports
        uses: dorny/test-reporter@v1
        if: always()
        with:
          artifact: pytest-results
          name: Pytest Report
          path: reports/pytest_junit_*.xml
          reporter: java-junit
